# Generated by Django 3.1.1 on 2020-10-15 18:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadEconomica',
            fields=[
                ('codActividadEconomica', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombreActividadEconomica', models.CharField(max_length=100)),
                ('descripcionActividadEconomica', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('codEmpresa', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(max_length=100)),
                ('descripcionEmpresa', models.CharField(blank=True, max_length=250)),
                ('codActividadEconomica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.actividadeconomica')),
            ],
        ),
        migrations.CreateModel(
            name='RazonesFinanciera',
            fields=[
                ('codRazon', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreRazon', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('codRubro', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreRubro', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('codSector', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombreSector', models.CharField(max_length=100)),
                ('descripcionSector', models.CharField(blank=True, max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='TipoCuenta',
            fields=[
                ('codTipoCuenta', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('nombreTipoCuenta', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ratio',
            fields=[
                ('codRatio', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreRatio', models.CharField(max_length=100)),
                ('codRazon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.razonesfinanciera')),
            ],
        ),
        migrations.CreateModel(
            name='CatalogoCuenta',
            fields=[
                ('codCuenta', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('nombreCuenta', models.CharField(max_length=100)),
                ('codEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.empresa')),
                ('codRubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.rubro')),
                ('codTipoCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.tipocuenta')),
            ],
            options={
                'unique_together': {('codEmpresa', 'codCuenta')},
            },
        ),
        migrations.CreateModel(
            name='RatiosSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametroComparacion', models.DecimalField(decimal_places=2, max_digits=6)),
                ('codRatio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ratio')),
                ('codSector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.sector')),
            ],
            options={
                'unique_together': {('codSector', 'codRatio')},
            },
        ),
        migrations.CreateModel(
            name='RatiosEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valorRatioEmpresa', models.DecimalField(decimal_places=2, max_digits=6)),
                ('codEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.empresa')),
                ('codRatio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ratio')),
            ],
            options={
                'unique_together': {('codEmpresa', 'codRatio')},
            },
        ),
        migrations.CreateModel(
            name='CuentaBalance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=2, max_digits=6)),
                ('codCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.catalogocuenta')),
                ('codEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.empresa')),
            ],
            options={
                'unique_together': {('codEmpresa', 'codCuenta', 'año')},
            },
        ),
    ]
