# Generated by Django 3.1.1 on 2020-11-06 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalisisVertical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('valor', models.DecimalField(decimal_places=3, max_digits=10)),
                ('codCuenta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.catalogocuenta')),
                ('codEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.empresa')),
                ('codRubro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.rubro')),
            ],
            options={
                'unique_together': {('codEmpresa', 'codCuenta', 'año')},
            },
        ),
    ]
