# Generated by Django 3.1.1 on 2020-10-15 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividadeconomica',
            name='descripcionActividadEconomica',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='descripcionEmpresa',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sector',
            name='descripcionSector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
