# Generated by Django 3.1.1 on 2020-11-12 06:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatiosEmpresaSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('año', models.IntegerField()),
                ('valorSector', models.DecimalField(decimal_places=3, max_digits=18)),
                ('promEmpresas', models.DecimalField(decimal_places=3, max_digits=18)),
                ('empresasQueCumplen', models.CharField(max_length=250)),
                ('codRatio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ratio')),
                ('codSector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.sector')),
            ],
            options={
                'unique_together': {('codSector', 'año', 'codRatio')},
            },
        ),
        migrations.DeleteModel(
            name='RatiosSector',
        ),
    ]
