# Generated by Django 3.1.1 on 2020-11-12 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0002_auto_20201112_0012'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatiosSector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parametroComparacion', models.DecimalField(decimal_places=3, max_digits=18)),
                ('codActividadEconomica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.actividadeconomica')),
                ('codRatio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.ratio')),
            ],
            options={
                'unique_together': {('codActividadEconomica', 'codRatio')},
            },
        ),
    ]
