# Generated by Django 3.1.1 on 2020-11-12 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_ratiossector'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratiosempresasector',
            name='codActividadEconomica',
            field=models.ForeignKey(default='MIN', on_delete=django.db.models.deletion.CASCADE, to='proyecto.actividadeconomica'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='ratiosempresasector',
            unique_together={('codActividadEconomica', 'año', 'codRatio')},
        ),
        migrations.RemoveField(
            model_name='ratiosempresasector',
            name='codSector',
        ),
    ]
