# Generated by Django 3.1.1 on 2020-10-26 04:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0003_auto_20201025_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadeconomica',
            name='codSector',
            field=models.ForeignKey(default='SEST', on_delete=django.db.models.deletion.CASCADE, to='proyecto.sector'),
            preserve_default=False,
        ),
    ]
