# Generated by Django 3.1.1 on 2020-11-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0004_auto_20201112_0039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ratiosempresasector',
            name='empresasQueCumplen',
        ),
        migrations.AddField(
            model_name='ratiosempresasector',
            name='empresasCumplenEmpresa',
            field=models.CharField(default=' ', max_length=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ratiosempresasector',
            name='empresasCumplenSector',
            field=models.CharField(default='No', max_length=300),
            preserve_default=False,
        ),
    ]
