# Generated by Django 3.1.1 on 2020-11-16 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('ADM', 'Administrador'), ('GER', 'Gerente'), ('EMP', 'Empleado')], default='EMP', max_length=3),
        ),
    ]
