# Generated by Django 3.1.1 on 2020-11-17 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('usuario', '0005_auto_20201116_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codEmpresa',
            field=models.ForeignKey(default='EMP', on_delete=django.db.models.deletion.CASCADE, to='proyecto.empresa'),
        ),
    ]
