# Generated by Django 3.1.1 on 2020-11-17 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proyecto', '0001_initial'),
        ('usuario', '0006_auto_20201116_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='codEmpresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proyecto.empresa'),
        ),
    ]
